Don`t abort catalog if template not exist
I the domain template file will be created by the same puppet run, which creates the domain, the catalog run fails with the following error:

Error: Failed to apply catalog: Parameter template failed on Domain[domain-test]: /home/glass/template.jar does not exist at /etc/puppetlabs/code/environments/production/..

We don`t need to check if the file is there in the domain type.